### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by mubashir-rehman** [UsmanGill-UG/Technical-Interview-Questions-Guide#1]
Kindly consider submitting it to the [awesome](https://github.com/sindresorhus/awesome) repository or a more specific one [awesome interview questions](https://github.com/DopplerHQ/awesome-interview-questions).

If you want to maintain your repository to follow some other direction like focusing only towards Pakistani software companies. Then, consider following [awsome repository contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/contributing.md), because they have had a fare amount of contributions already.

**Comment by UsmanGill-UG** [comment]
Sure, will do.
